version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iot-dev-starting-book-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o67sbzrq7wg"
s3_prefix = "iot-dev-starting-book-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

